### ISSUE TITLE
Terminology: Traveller vs. Traveler

### ISSUE THREAD

**Issue by aschrijver** [OpenHospitalityNetwork/openHospitality.network#18]
Traveller, travelling and traveler, traveling are all correct use of language. The first variant is UK / international and the second is US-flavored apparently. There's a good explanation on the distinction at Grammarly's [Traveling or Travelling?](https://www.grammarly.com/blog/traveling/) blog post.

The terminology we choose might be used in any or all of these locations:

- Communication, documentation
- Domain models & designs
- Code, UI's and tests

Imho, it is important to make a choice and settle on one preferred spelling, both for consistency and to avoid confusion and even bugs.

**Comment by aschrijver** [comment]
**Note**: the choice may be even broader. If the encodings used is `en-US` then maybe everywhere we need to prefer US terminology everywhere, versus UK spelling when encoding is British.

**Comment by weex** [comment]
Even though I never knew it, the second feels more natural to me. That being said I think the userbase is likely to prefer the former, so let's go with that.

A PR doesn't really make sense for this so I created the home page in the wiki and a Glossary with just one term: https://github.com/FediHospEx/fedihospex.github.io/wiki/Glossary
