### ISSUE TITLE
Problem: Seeing widget notification badge in chat for unclear reason

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/openHospitality.network#38]
Not sure if this is mobile app specific but for the Matrix chat room, I see a red badge on the widget for the pad (WondrousGigaDisaster) but if I click into it I have no idea why I'm seeing the badge. Here's the top of my Element matrix app. 
![Screenshot_20210723-103603](https://user-images.githubusercontent.com/38776/126830847-c05c21ed-5c34-419a-9c1c-3ddcf50d36f3.png)

**Comment by mariha** [comment]
I've unpinned the pad and it disappeared. I thought it was a global action but maybe everyone in the room has to do the same? Not sure. 

@chagai95 is it ok to remove the pad, if it's not gone yet?

**Comment by chagai95** [comment]
Done
