### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/openHospitality.network#40]
**One step back: why separate repo?**

Our project is more then fedi-trustroots, we need to separate organization-wide issues (other federation ideas and process related). Once we white-label trustroots codebase (fairtravellers), we may abstract an open hospitality exchange protocol so that other communities can join, we may change backend or start as a plugin to go-fed, frendica, bonfire or other ActivityPub based app.

### What name?

- website?
   It's more ten the website, it's bucket for project (gh organization) -wide issues, website, federation and process related. They are available to public via this website though.
- website + separate place (repo?) for [meta], open organization and project-wide (federation) stuff? 
   GH in general is not good for non-linear exploration nor for non-technical people for whom there is overwhelming amount of distracting and irrelevant stuff in the gui all over around
   Discourse would be better then GH issues/discussions, we also have trello. 
- **openHospitality.network** ?
- docs? process? organization-wide?

### todo:
- [x] rename in project settings
- [x] trello links
- [x] anywhere else? (in general I used rather link to the organization not the project itself)

**Comment by weex** [comment]
Project or Ops both sounds good to me but the thing is this repo is connected to the website so perhaps create a new one and then transfer non-site-related issues over to that repo. I actually don't mind the comingling because it's one less place to check.

**Comment by mariha** [comment]
I finally renamed it to `openHospitality.network`. Looks like nothing else is needed, GH automatically redirects old links to the new repo (in trello for example).

@aschrijver I think you'll be happy to see the new name ;)

**Comment by aschrijver** [comment]
Yay :partying_face:

**Comment by mariha** [comment]
I changed `openHospitality.network` repo name back to `openHospitalityNetwork.github.io` because I couldn't set `ALIAS` DNS record of https://openHospitality.network to point to `openHospitalityNetwork.github.io/openHospitality.network`. Feels like there should be a way to do it, but it was not clear for me how at the moment. 

It's best what I could do. Except ugly and non-informative repo name, everything else should work well.
