### ISSUE TITLE
Problem: demo.openhospitality.network is running on a personal account

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/openHospitality.network#46]
I set this up on my personal Digital Ocean account but wanted to transfer it to a better team setup.

I created a Team in DO and added @mariha to that team. A snapshot was created from the original droplet which has been restored to a new droplet in region AMS3. That droplet and web application is now up and running at 68.183.12.199. The last step to transition is to switch DNS to point to this IP and turn off my personal droplet.

**Comment by mariha** [comment]
I updated it, should be good once the change propagates.
